name: CI
on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check if the code is formatted according to Deno's default formatting conventions
        run: deno fmt --ignore="**/*.md"

      - name: Scan the code for syntax errors and style issues.
        run: deno lint

      - name: Run all test files in the repository
        run: deno test --allow-all
