name: CI
on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.0.1

      - name: Test
        run: deno test

      - name: Lint
        run: deno lint

      - name: Format
        run: deno fmt --check
